name: Build iOS .dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Theos Environment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        brew install ldid xz
        export THEOS=~/theos
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        echo "THEOS=$THEOS" >> $GITHUB_ENV
        echo "$THEOS/bin" >> $GITHUB_PATH

    - name: Download and Rename iOS SDK
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p $THEOS/sdks
        curl -fSL -o iPhoneOS16.5.sdk.tar.xz https://github.com/theos/sdks/raw/master/iPhoneOS16.5.sdk.tar.xz
        tar -xf iPhoneOS16.5.sdk.tar.xz -C $THEOS/sdks
        rm iPhoneOS16.5.sdk.tar.xz
        if [ -d "$THEOS/sdks/iPhoneOS16.5.sdk" ]; then
          mv $THEOS/sdks/iPhoneOS16.5.sdk $THEOS/sdks/iPhoneOS.sdk
        fi

    - name: Compile Tweak to Dylib
      run: |
        make
        mkdir -p output_artifacts
        find .theos/obj/ -name "*.dylib" -exec cp {} output_artifacts/ \; || true

    - name: Upload Dylib Artifact
      uses: actions/upload-artifact@v4
      with:
        name: YouTubeX-Dylib-File
        path: output_artifacts/*.dylib
